version: "3.8"
networks:
  airflow:

services:
    redis:
        image: redis:6.0.8-alpine
        environment:
          REDIS_HOST: redis
          REDIS_PORT: 6379
        ports:
          - 6379:6379
        # command: redis-server --requirepass redispass
        networks:
          - airflow

    postgres:
        image: postgres:13.0
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
            - PGDATA=/var/lib/postgresql/data/pgdata
        ports:
          - 5432:5432
        volumes:
          - ./database/data:/var/lib/postgresql/data/pgdata
          - ./database/logs:/var/lib/postgresql/data/log
        command: >
          postgres
            -c listen_addresses=*
            -c logging_collector=on
            -c log_destination=stderr
            -c max_connections=200
        networks:
          - airflow

    webserver:
        image: docker-airflow:latest
        restart: always
        depends_on:
            - postgres
            - redis
        environment:
            - LOAD_EX=n
            - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
            - EXECUTOR=Celery
            # - POSTGRES_USER=airflow
            # - POSTGRES_PASSWORD=airflow
            # - POSTGRES_DB=airflow
            # - REDIS_PASSWORD=redispass
        volumes:
            - ./dags:/usr/local/airflow/dags
            - ./logs:/usr/local/airflow/logs
            # Uncomment to include custom plugins
            # - ./plugins:/usr/local/airflow/plugins
        ports:
            - "8080:8080"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3
        networks:
          - airflow

    flower:
        image: docker-airflow:latest
        restart: always
        #env_file:
          #- .env
        depends_on:
            - redis
        environment:
            - EXECUTOR=Celery
            # - REDIS_PASSWORD=redispass
        volumes:
          - ./logs:/usr/local/airflow/logs
        ports:
            - "5555:5555"
        command: flower
        networks:
          - airflow

    scheduler:
        image: docker-airflow:latest
        restart: always
        depends_on:
            - webserver
        volumes:
            - ./dags:/usr/local/airflow/dags
            - ./logs:/usr/local/airflow/logs
            # Uncomment to include custom plugins
            # - ./plugins:/usr/local/airflow/plugins
        environment:
            - LOAD_EX=n
            - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
            - EXECUTOR=Celery
            # - POSTGRES_USER=airflow
            # - POSTGRES_PASSWORD=airflow
            # - POSTGRES_DB=airflow
            # - REDIS_PASSWORD=redispass
        command: scheduler
        networks:
          - airflow

    worker:
        image: docker-airflow:latest
        restart: always
        depends_on:
            - scheduler
        volumes:
            - ./dags:/usr/local/airflow/dags
            - ./logs:/usr/local/airflow/logs
            # Uncomment to include custom plugins
            # - ./plugins:/usr/local/airflow/plugins
        environment:
            - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
            - EXECUTOR=Celery
            # - POSTGRES_USER=airflow
            # - POSTGRES_PASSWORD=airflow
            # - POSTGRES_DB=airflow
            # - REDIS_PASSWORD=redispass
        command: worker
        networks:
          - airflow